# Generated by Django 4.1.3 on 2022-12-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="create_on",
            new_name="created_on",
        ),
    ]
