# Generated by Django 4.1.3 on 2022-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="uploads/profile_pictures/default.png",
                upload_to="uploads/profile_pictures",
            ),
        ),
    ]
