# Generated by Django 4.1.3 on 2022-12-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_alter_userprofile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="localtion",
            new_name="location",
        ),
    ]
